OPTIMIZER:
    LEARN_RATE: 0.00005
    BACKBONE_LR_MULT: 0.0
    EMBEDDER_LR_MULT: 3.0
    CLASSIFIER_LR_MULT: 3.0
    WEIGHT_DECAY: 0.0005
DATA:
    BATCH_SIZE: 32
    IDS_PER_BATCH: 2
    WIDTH: 256
    HEIGHT: 128
SINGLE_HEAD: false
GLOBAL_TRIPLET_LOSS: false
NETWORK_INPUT_KEY: imgs
CLASSIFICATION_LOSS:
    NAME: CROSS_ENTROPY
TRIPLET_LOSS:
    NAME: HARD_BATCH_TRIPLET
    KWARGS:
        margin: 1
TRIPLET_WEIGHT: 1.0